### ISSUE TITLE
Call to undefined function WP_Filesystem()

### ISSUE THREAD

**Issue by gllmhyt** [benbalter/wordpress-static-site-exporter#24]
The script fails to export my Wordpress 3.5.1 install (considering a nice export for a future Jekyll site) : Debian Wheezy is up-to-date, with PHP 5.4.16 from DotDeb and MariaDB 5.5.31 from MariaDB repositories.

```
php jekyll-export-cli.php > jekyll-export.zip
PHP Fatal error:  Call to undefined function WP_Filesystem() in /var/www/wordpress/wp-content/plugins/wordpress-to-jekyll-exporter/jekyll-export.php on line 237
```

I don't know where to search for a fix.

**Comment by ken-wong** [comment]
> I fixed this by adding the following include to jekyll-export-cli.php after the existing one:
> 
> ```
> include "../../../wp-admin/includes/file.php";
> ```

Even 10 years passed, your comment still works for me.
And I have no idea why it's not been fixed.

**Comment by colordancer** [comment]
> > I fixed this by adding the following include to jekyll-export-cli.php after the existing one:
> > ```
> > include "../../../wp-admin/includes/file.php";
> > ```
> 
> Even 10 years passed, your comment still works for me. And I have no idea why it's not been fixed.

same opinion. It's so terrible that this bug keeps unfixed for ten years.

**Comment by benbalter** [comment]
This was fixed in 2013 via https://github.com/benbalter/wordpress-to-jekyll-exporter/pull/26. That line was removed in 2020 via https://github.com/benbalter/wordpress-to-jekyll-exporter/pull/189.

We could possibly add it back in, with a check if `get_file_description` is defined which should work in both cases. Happy to review a PR.
