### ISSUE TITLE
Invalid zip file

### ISSUE THREAD

**Issue by sammydigits** [benbalter/wordpress-static-site-exporter#31]
Using Wordpress 3.9.1 (latest as of August 1st 2014), the zip file is created and downloaded successfully, it is 3.8 MB file in size, but cannot be extracted, windows claims its an invalid zip file.

Thanks

**Comment by Joshfindit** [comment]
Running on MediaTemple's wp host in single-site configuration with Wordpress 4.2.4 and Exporter 2.0.1.

Came here because I have the same issue; zip file invalid, and the error is the same as @johnbuck.

**Comment by IanMayo** [comment]
@benbalter - this issue seems to have returned.  Or, a different issue is causing the same symptom.  I'm using hosted WordPress 4.9.8, with version 2.2.3 of the exporter.

I get the above issue when I try to expand the zip.  But, since the zip is so small, I tried to look inside it directly, and found this text:
````
<br />
<b>Fatal error</b>:  Unknown: Cannot use output buffering in 
output buffering display handlers in <b>Unknown</b> on 
line <b>0</b><br />
````

That looks like an error is being thrown by the export process, which is then being downloaded as a zip.
